### PR TITLE
Added Rubat's Achievement viewer

### PR DESCRIPTION
**Pull request by L1Q**
Basically took the achievement viewer addon and put it into the menu system.
Could be another feature of this menu ;D

### CODE REVIEW

**Comment by Kefta** [comment]
Why'd you fork off my fork :v:

**Comment by L1Q** [comment]
Noob here xD.
How do I fork original & add your commits BTW?

**Comment by Kefta** [comment]
You can't move the forks now; just leave it

**Comment by robotboy655** [comment]
I added it properly @ https://github.com/robotboy655/gmod-lua-menu/commit/5dead2a3a2825465ff03b213afdfbf01b723e64b

**Comment by L1Q** [comment]
Thx :D

**Pull request closed without merging**
